**Find players and player IDs**
https://github.com/swar/nba_api/blob/master/docs/table_of_contents.md

In [42]:
from nba_api.stats.static import players
import pandas as pd

**Create a dictionary to get players**

In [43]:
player_dict = players.get_players()

**Use a for loop to find players by their "full_name"**

In [44]:
goat = [player for player in player_dict if player['full_name'] == 'LeBron James'][0]
goat_id = goat['id']

In [45]:
print(goat_id)

2544

**Create a dictionary to get teams**

In [46]:
from nba_api.stats.static import teams
team_dict = teams.get_teams()

**Use a for loop to find teams by their "team_name"**

In [47]:
celtics = [team for team in team_dict if team['full_name'] == 'Boston Celtics'][0]
celtics_id = celtics['id']

In [48]:
print(celtics_id)

1610612738

**Retreiving game logs for a specific season and player**

In [60]:
from nba_api.stats.endpoints import playergamelog

gamelog_goat = playergamelog.PlayerGameLog(player_id = '2544', season = '2024-25')
print(gamelog_goat)

gamelog_goat_df = gamelog_goat.get_data_frames()[0]

gamelog_goat_df.head()

<nba_api.stats.endpoints.playergamelog.PlayerGameLog object at 0x000001C102C23CE0>

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,...,4,4,8,1,0,1,1,14,5,1
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,...,5,7,3,1,0,2,2,27,18,1
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,...,7,7,3,1,0,6,1,28,-23,1
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,...,1,3,7,1,0,2,0,19,7,1
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,...,0,0,8,2,0,1,1,27,7,1

**Retrieving game logs for all seasons for a specific player**

In [66]:
from nba_api.stats.library.parameters import SeasonAll

gamelog_goat_all_seasons = playergamelog.PlayerGameLog(player_id=goat_id, season = SeasonAll.all)
df_goat_games_all_seasons = gamelog_goat_all_seasons.get_data_frames()[0]
df_goat_games_all_seasons.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,2544,0022401185,"Apr 11, 2025",LAL vs. HOU,W,22,6,11,0.545,...,4,4,8,1,0,1,1,14,5,1
1,22024,2544,0022401159,"Apr 09, 2025",LAL @ DAL,W,36,11,20,0.550,...,5,7,3,1,0,2,2,27,18,1
2,22024,2544,0022401153,"Apr 08, 2025",LAL @ OKC,L,35,8,19,0.421,...,7,7,3,1,0,6,1,28,-23,1
3,22024,2544,0022401135,"Apr 06, 2025",LAL @ OKC,W,34,9,16,0.563,...,1,3,7,1,0,2,0,19,7,1
4,22024,2544,0022401126,"Apr 04, 2025",LAL vs. NOP,W,33,9,17,0.529,...,0,0,8,2,0,1,1,27,7,1

**Retrieving all the game logs from a team**

In [69]:
from nba_api.stats.endpoints import leaguegamefinder
celtics_games = leaguegamefinder.LeagueGameFinder(team_id_nullable = celtics_id).get_data_frames()[0]
celtics_games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612738,BOS,Boston Celtics,1522500074,2025-07-20,BOS vs. ATL,W,201,101,...,0.727,13,31,44,24,9,5,12,10,21.0
1,22025,1610612738,BOS,Boston Celtics,1522500058,2025-07-17,BOS @ LAL,W,200,87,...,0.682,15,27,42,21,13,3,16,21,9.0
2,22025,1610612738,BOS,Boston Celtics,1522500035,2025-07-14,BOS @ MIA,L,200,96,...,0.810,9,26,35,26,12,3,15,30,-4.0
3,22025,1610612738,BOS,Boston Celtics,1522500026,2025-07-13,BOS vs. NYK,W,201,94,...,0.793,10,28,38,19,14,5,16,31,13.0
4,22025,1610612738,BOS,Boston Celtics,1522500008,2025-07-11,BOS vs. MEM,W,200,92,...,0.697,16,29,45,17,5,9,17,20,14.0